name: eClear Lagos Sync

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:      # Allows you to run it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Sync Script
        run: python sync_tix.py
        env:
          PREDICTHQ_TOKEN: ${{ secrets.PREDICTHQ_TOKEN }}

      - name: Push Updates to Repository
        run: |
          git config --global user.name "eClear Sync Bot"
          git config --global user.email "actions@github.com"
          git add events.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "🔄 Auto-sync: Updated Lagos events" && git push)